### PR TITLE
feat (refactoring organisation) : Maven compliant

### PR DESCRIPTION
**Pull request by KilianStein**
Thanks you for this nice big update.

I used to include restapi_context in my bonita rest api and i have some trouble to synchronise restapi_context with my local rest extension api. I found what is missing for this projet : a maven compliancy.

Features of this commit
- refactoring project organization to be maven compliant.
- merge DocumentPermissionRule with ContextAccess API Rest to delete code duplication and simplify maintenance
- generated release files (*.bos, *.zip, .pdf) to target dir in package maven phase 
- created a doc dir for exemple and documentation *.bos and *.pdf stored by version
- compliant with import src in bonita_project/restAPIExtension/ContextAccess

All you have to do is "maven clean install"

Is it working for you ? What do you think of it ?

PS : DocumentPermissionRule-2.8.zip contains script groovy with packahe header. i don't know if it a matter !?

Some screenshots :

capture

capture

### CODE REVIEW

**Comment by pierre-yves-monnet** [comment]
Hello Kilian, this is great !
Yes,in the Permission Rule, we must NOT HAVE ANY PACKAGES. This is a big concern here because:
* the permission rule does not accept any package, 
* and any Java

In the next release, I would like to move some part in JAVA, but if you could change the Permission Script and remove the package, then I can accept the PullRequest and create a 2.9 version.

Thanks for your contribution !

**Comment by KilianStein** [comment]
Thanks for this reply.

Here my commit with deleting package support on permission rule release

I don't know which part of ContextAccess you want to move in java so i didn't work on it. I think the best solution would be to change file extension groovy to java to get compiler java compliance. The hard part is to make it work for both "restApiExtension" and "PermissionRule"
Why would you move theses script into java ? Do you want to include this code into bonita core ?

Regards

**Comment by pierre-yves-monnet** [comment]
hello,
I checked all the different files, and your proprosition is very nice.
I'll accepted it right now.
I love the fact that we can use the same class to generate the DocumentPermissionContextRule from the same class. I will see that after the merge (I tried a mvn install and it's failed because there are some missing file of course). We must be sure that the documentzip is correct (no package name).
I got this when I do a mvn install
        import java.time.format.DateTimeFormatter;
                                ^^^^^^^^^^^^^^^^^
Groovy:unable to resolve class java.time.format.DateTimeFormatter

My java machine per default is the 1.8. Do you know why the groovy compiler use the JDK 1.7 ? I saw:
[INFO] Using Groovy-Eclipse compiler to compile both Java and Groovy files


For your next question:
I don't know which part of ContextAccess you want to move in java 
=> Well, all in fact, to speed up the calculation ! Actually, the Groovy part is write as JAVA, do you think it's possible, by maven, to create a RestApiZip file where:
* the RestContextHandleGet.groovy stay in groovy (we must for the Bonita REST API CONTEXT mechanism)
* all another file are transform to JAVA and then compiled in a JAVA LIB
* then the final RestApiZip file created with all this part ? 

It will be amazing : keep in in Groovy for the Studio, to test and develop it
When we create a release, use JAVA to speed up the result (to be honest, I don't know if the JAVA will be faster than Groovy, but R&D told us the JAVA is 7 to 8 time faster than Groovy).
If this works, then I will create a RestContextHandleGetV2 very small, immediately call a another RestContextHandleGetJava to speed up as possible.

Thanks again for your contribution

**Comment by KilianStein** [comment]
Hello,

I forget to commit untrack file, my bad :(, sorry (i created a pull request with assembly file).

I have no problem with java version 1.8 and the compilation work for me ... i dont know how to help you. can you check your JAVA_HOME is you path system ?

For java purpose, i undertand your performance needs. There are 3 solutions faster to slower : 
1) Java -compileJar-> byteCode -read-> InterpreterExecution
2) Groovy -compileJar-> byteCode -read-> InterpreterExecution
3) Groovy -compileAndRead-> ScriptInterpreterExecution

I made some tests with soapUI loadTest :

Scenario 3 : with all groovy script (load Test parameter : 5 threads with 1000ms delay for 60s)
2 8-groovy

Scenario 2 : with only groovy RestContextHandleGet.groovy and the other in jar (load Test parameter : 5 threads with 1000ms delay for 60s)
2 8-withjar
If you want to test Scenario 2 all you have to do is to change value in assemblyContextAccessZip.xml
-> put `<include>**/RestContextHandleGet.groovy</include>` intead of `<include>**/*</include>`
-> set `<useProjectArtifact>true</useProjectArtifact>` intead of `<useProjectArtifact>false</useProjectArtifact>`
and you will have a ContextAccess-2.8.zip with your project jar lib

My Tests Conclusions
We have to make more tests. In this 2 tests, the delta time in not enough to say that Scenario 2 is the things to do to gain exception time. 
To my mind, if you want to have big gain speed execution, you have to focus on database access.

What do you think of it ?

**Pull request merged**
